# Generated by Django 4.2.1 on 2023-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image_url",
            field=models.ImageField(default="No_Image_Available.jpg", upload_to=""),
        ),
    ]
